# Базовый образ
FROM python:3.9-slim

# Установка зависимостей для скачивания и распаковки
RUN apt-get update && \
    apt-get install -y wget unzip && \
    rm -rf /var/lib/apt/lists/*

# Рабочая директория в контейнере
WORKDIR /app

# Скачивание архива с Google Диска и распаковка
ENV FILE_ID=1kvOp-KOck6-44vnTSd8g4pnk8O1DrOk4
RUN wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O chest_xray.zip && \
    unzip chest_xray.zip && \
    rm chest_xray.zip

# Копирование файлов проекта
COPY . .

# Установка зависимостей Python
RUN pip install --no-cache-dir -r requirements.txt

# Команда по умолчанию
CMD ["python", "test.py"]
